services:
  ui:
    build:
      dockerfile: ui/Dockerfile.ui
    working_dir: /app
    volumes:
      - ./ui/src:/app/src  # Mount your local repo dir to /app dir
      - ./ui/public:/app/public  # Mount your local repo dir to /app dir
      - ./ui/node_modules:/app/node_modules  # Mount your local repo dir to /app dir
    ports:
     - "3000:3000"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    # command: ["nginx", "-g", "daemon off;"]
    command: ["npm", "start"]
    depends_on:
      - apiserver
    networks:
      - local
  apiserver:
    image: python:3.10
    build:
      dockerfile: api_server/Dockerfile.api
    volumes:
      - .:/app  # Mount your local repo dir to /app dir
    working_dir: /app 
    command: ["uvicorn", "api_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Command to run the FastAPI app
    ports:
      - "8000:8000"  # Expose port 8000 for FastAPI
    environment:
      - PYTHONUNBUFFERED=1  # Optional: Ensure logs are flushed immediately
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=phil
    depends_on:
      - db
    networks:
      - local
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phil
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - local
  ubuntu:
    build:
      dockerfile: Dockerfile.ubuntu
    depends_on:
      - db
    environment:
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=phil
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - local
    # command: ["/bin/bash", "source sqlAlchemy/bin/activate; python3 /app/create_database.py"]
volumes:
  pgdata:
networks:
  local:
    driver: bridge  # Using bridge network
